### ISSUE TITLE
Treemendous has failed to load correctly

### ISSUE THREAD

**Issue by DatrixTHLK** [rehwinkel/treemendous#1]
Hi there,

It appears that the newest forge version 34.1.32 has broken your mod. If you already know about this, then you may ignore it. I just thought you'd like to be kept in the loop.

**Comment by WenXin20** [comment]
Hello, I also got this crash using Forge v34.1.33:
<details>
  <summary>Error Log</summary>
  
  ```
[00:51:27] [modloading-worker-3/ERROR]: Failed to create mod instance. ModID: treemendous, class deerangle.treemendous.main.Treemendous
java.lang.ExceptionInInitializerError: null
	at deerangle.treemendous.main.Treemendous.<init>(Treemendous.java:36) ~[?:1.16.3-0.4.1]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_51]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[?:1.8.0_51]
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_51]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) [?:34.1]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer$$Lambda$3108/1719999141.run(Unknown Source) [?:34.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:110) [?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3422/1010419513.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
Caused by: java.lang.IllegalStateException: Can not register to a locked registry. Modder should use Forge Register methods.
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:56) ~[?:?]
	at net.minecraftforge.registries.NamespacedWrapper.register(NamespacedWrapper.java:72) ~[?:?]
	at net.minecraftforge.registries.NamespacedWrapper.func_218381_a(NamespacedWrapper.java:40) ~[?:?]
	at net.minecraft.util.registry.Registry.func_218322_a(Registry.java:456) ~[?:?]
	at net.minecraft.util.registry.Registry.func_218325_a(Registry.java:452) ~[?:?]
	at deerangle.treemendous.world.TreeWorldGenRegistry.registerFoliagePlacerType(TreeWorldGenRegistry.java:36) ~[?:1.16.3-0.4.1]
	at deerangle.treemendous.world.TreeWorldGenRegistry.<clinit>(TreeWorldGenRegistry.java:16) ~[?:1.16.3-0.4.1]
	... 16 more
  ```
  
</details>

**Comment by rehwinkel** [comment]
Newest commit fixes this issue. The newest mod release (0.4.2) should be up on curseforge in a couple of minutes.

**Comment by DatrixTHLK** [comment]
Thank you!
